sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jck8s/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true jck8s/react-test npm test -- --coverage

after_success:
  # Build the production services
  - docker build -t jck8s/multi-client ./client
  - docker build -t jck8s/multi-nginx ./nginx
  - docker build -t jck8s/multi-server ./server
  - docker build -t jck8s/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the images to Docker Hub
  - docker push jck8s/multi-client
  - docker push jck8s/multi-nginx
  - docker push jck8s/multi-server
  - docker push jck8s/multi-worker